<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP-000873.local" failures="2" tests="21" name="Login Page Test" time="44.402" errors="0" timestamp="2025-07-26T13:34:53 IST">
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.304">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="forgotPwdLinkExistTest" time="5.926"/>
  <testcase classname="com.qa.crm2.tests.SearchResultsTest" name="searchResultsCountTest" time="2.776"/>
  <testcase classname="com.qa.crm2.tests.SearchResultsTest" name="searchResultsCountTest" time="1.011"/>
  <testcase classname="com.qa.crm2.tests.SearchResultsTest" name="searchResultsCountTest" time="0.716"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.085">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.088">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.ProductPageInfoTest" name="addItemTest" time="6.255"/>
  <testcase classname="com.qa.crm2.tests.SearchResultsTest" name="searchResultsTest" time="2.097"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.084">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.659">
    <failure type="java.lang.AssertionError" message="=====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: =====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.qa.crm2.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageUrlTest" time="5.014"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginTest" time="1.108"/>
  <testcase classname="com.qa.crm2.tests.ProductPageInfoTest" name="productHeaderTest" time="7.969"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="7.149">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.ProductPageInfoTest" name="productHeaderTest" time="2.192"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.1">
    <failure type="java.lang.AssertionError" message="=====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: =====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.qa.crm2.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageUrlTest" time="0.015"/>
  <testcase classname="com.qa.crm2.tests.ProductPageInfoTest" name="productHeaderTest" time="2.126"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginTest" time="3.256"/>
  <testcase classname="com.qa.crm2.tests.ProductPageInfoTest" name="productHeaderTest" time="6.986"/>
</testsuite> <!-- Login Page Test -->
